version: '3'

services:
  embedding-dev:
    build:
      context: .
    volumes:
      - ./embedding:/src/embedding
      - ./plots:/src/plots
      - ./ai:/ai
    ports:
      - 10001:9090
    environment:
    - AI_CHAT_CAPACITY=1
    - AI_TRAIN_CAPACITY=1
    - EMB_SERVER_PORT=9090
    # - W2V_SERVER_URL=http://ai-word2vec:9090
    - W2V_SERVER_URL=http://dev.hutoma.com:8081
