version: '3'

services:
#   Assumes word2vec GIT is in same parent folder as embedding GIT.
  ai-word2vec:
    build:
      context: ../../word2vec/src
      dockerfile: Dockerfile
    volumes:
      - ../../word2vec/src/word2vec:/src/word2vec
      - ../../word2vec/src/datasets:/datasets
#      - /mnt/storage/thomas/word_vectors/:/datasets
    ports:
      - 10002:9090
    environment:
    - W2V_SERVER_PORT=9090
    - W2V_VECTOR_FILE=/datasets/glove.840B.300d.txt
  
  api-entity:
    build:
      context: ../../entity_recognizer/src
      dockerfile: Dockerfile
    ports:
      - 10003:9095
    environment:
    - ERS_MINIMAL_SERVER=1

  ai-embedding:
    build:
      context: .
    volumes:
      - ./embedding:/src/embedding
      - ./ai:/ai
    ports:
      - 10001:9090
    environment:
    - AI_CHAT_CAPACITY=1
    - AI_TRAIN_CAPACITY=1
    - EMB_SERVER_PORT=9090
    # - W2V_SERVER_URL=http://ai-word2vec:9090
    - W2V_SERVER_URL=http://10.8.0.26:9090
#    - W2V_SERVER_URL=http://10.181.0.4:30100
    - EMB_SERVER_URL=http://10.8.0.26:8097
